name: Banking

on:
  push:
      branches: 
      - main
      
jobs:

  BuildProject:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: build banking
          shell: bash
          run: |
            cd banking
            cmake -H. -B_build
            cmake --build _build
